// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="relu,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7vx485t-ffg1157-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.190000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=49,HLS_VERSION=2019_2}" *)

module relu (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        ap_return
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
output  [31:0] ap_return;

wire   [0:0] icmp_ln3_fu_20_p2;
wire   [30:0] trunc_ln3_fu_26_p1;
wire   [30:0] select_ln3_fu_30_p3;

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign ap_return = select_ln3_fu_30_p3;

assign icmp_ln3_fu_20_p2 = (($signed(a) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign select_ln3_fu_30_p3 = ((icmp_ln3_fu_20_p2[0:0] === 1'b1) ? trunc_ln3_fu_26_p1 : 31'd0);

assign trunc_ln3_fu_26_p1 = a[30:0];

endmodule //relu
